# Generated by Django 6.0.7 on 2026-07-23 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionare', models.TextField()),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluate.pillar')),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField()),
                ('score', models.IntegerField()),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='evaluate.questions')),
            ],
        ),
    ]
